In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel('/Users/didyvanbelkom/Documents/02 MSc DSS/THESIS CODE/Jupiter Notebook/df_complete.xlsx')

In [3]:
df.head()

Unnamed: 0  Customer_ID   recency  frequency  monetary  TotalPrice  \
0           0        12346  0.439678   0.049020  0.001059    77183.60   
1           1        12347  0.005362   0.004902  0.003782     4310.00   
2           2        12348  0.195710   0.000000  0.000628     1797.24   
3           3        12349  0.112601   0.009804  0.007642     1757.55   
4           4        12352  0.026810   0.004902  0.000976     2506.04   

   Top_10%_spend  
0              1  
1              1  
2              0  
3              0  
4              0

In [4]:
df.drop(columns=['Unnamed: 0'])

Customer_ID   recency  frequency  monetary  TotalPrice  Top_10%_spend
0           12346  0.439678   0.049020  0.001059    77183.60              1
1           12347  0.005362   0.004902  0.003782     4310.00              1
2           12348  0.195710   0.000000  0.000628     1797.24              0
3           12349  0.112601   0.009804  0.007642     1757.55              0
4           12352  0.026810   0.004902  0.000976     2506.04              0
...           ...       ...        ...       ...         ...            ...
2767        18278  0.104558   0.000000  0.000680      173.90              0
2768        18280  0.077748   0.000000  0.000872      180.60              0
2769        18281  0.568365   0.000000  0.000336       80.82              0
2770        18283  0.045576   0.024510  0.001830     2094.88              0
2771        18287  0.045576   0.014706  0.006710     1837.28              0

[2772 rows x 6 columns]

In [5]:
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

# import required libraries for clustering
import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from scipy.cluster.hierarchy import linkage
from scipy.cluster.hierarchy import dendrogram
from scipy.cluster.hierarchy import cut_tree

In [6]:
km = KMeans(n_clusters = 7)
km

KMeans(n_clusters=7)

In [7]:
np.random.seed(123)

In [8]:
y_predicted = km.fit_predict(df[['recency', 'frequency', 'monetary']])
y_predicted

array([4, 0, 2, ..., 1, 0, 0], dtype=int32)

In [9]:
df['cluster'] = y_predicted
df.head()

Unnamed: 0  Customer_ID   recency  frequency  monetary  TotalPrice  \
0           0        12346  0.439678   0.049020  0.001059    77183.60   
1           1        12347  0.005362   0.004902  0.003782     4310.00   
2           2        12348  0.195710   0.000000  0.000628     1797.24   
3           3        12349  0.112601   0.009804  0.007642     1757.55   
4           4        12352  0.026810   0.004902  0.000976     2506.04   

   Top_10%_spend  cluster  
0              1        4  
1              1        0  
2              0        2  
3              0        2  
4              0        0

In [10]:
df.value_counts()

Unnamed: 0  Customer_ID  recency   frequency  monetary  TotalPrice  Top_10%_spend  cluster
2771        18287        0.045576  0.014706   0.006710  1837.28     0              0          1
919         14403        0.600536  0.004902   0.001151  1475.81     0              1          1
927         14415        0.037534  0.044118   0.017724  5900.28     1              0          1
926         14414        0.024129  0.000000   0.002576  1496.98     0              0          1
925         14413        0.120643  0.009804   0.001846  122.70      0              2          1
                                                                                             ..
1847        16325        0.158177  0.039216   0.008593  594.24      0              2          1
1846        16323        0.568365  0.000000   0.000410  207.50      0              1          1
1845        16321        0.699732  0.004902   0.000653  373.65      0              1          1
1844        16320        0.235925  0.014706  

In [11]:
test = df.groupby(['cluster', 'Top_10%_spend']).count()

In [12]:
print(test['Customer_ID'])

cluster  Top_10%_spend
0        0                1115
         1                 288
1        0                 143
2        0                 607
         1                  52
3        0                  61
         1                   2
4        0                 177
         1                   6
5        0                 287
         1                  21
6        1                  13
Name: Customer_ID, dtype: int64


In [13]:
df_test = df.loc[df['cluster'] == 0]

In [14]:
df_test.describe()

Unnamed: 0   Customer_ID      recency    frequency     monetary  \
count  1403.000000   1403.000000  1403.000000  1403.000000  1403.000000   
mean   1425.173913  15429.025659     0.034805     0.031288     0.009231   
std     802.538821   1707.098846     0.025576     0.036981     0.017097   
min       1.000000  12347.000000     0.000000     0.000000     0.000078   
25%     739.500000  13994.000000     0.010724     0.009804     0.002108   
50%    1460.000000  15513.000000     0.029491     0.019608     0.004671   
75%    2126.500000  16924.500000     0.056300     0.039216     0.009551   
max    2771.000000  18287.000000     0.093834     0.333333     0.242118   

          TotalPrice  Top_10%_spend  cluster  
count    1403.000000    1403.000000   1403.0  
mean     3038.377670       0.205274      0.0  
std      8350.640631       0.404046      0.0  
min        15.000000       0.000000      0.0  
25%       483.525000       0.000000      0.0  
50%      1258.060000       0.000000      0.0  
75%      2975.120000       0.000000      0.0  
max    194550.790000       1.000000      0.0

In [15]:
df_test = df_test.drop(columns=['Unnamed: 0', 'Customer_ID', 'TotalPrice', 'cluster'])

In [16]:
df_test.head()

recency  frequency  monetary  Top_10%_spend
1  0.005362   0.004902  0.003782              1
4  0.026810   0.004902  0.000976              0
7  0.040214   0.009804  0.010194              0
8  0.061662   0.004902  0.034589              1
9  0.026810   0.009804  0.007779              0

In [17]:
df_test['Top_10%_spend'].value_counts()

0    1115
1     288
Name: Top_10%_spend, dtype: int64

In [18]:
X = df_test.drop(columns = ['Top_10%_spend'])
y = df_test['Top_10%_spend']

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=123)

In [ ]:
#Random Forest not using oversampling

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
rfc = RandomForestClassifier(n_estimators=100, random_state = 123)
rfc.fit(X_train,y_train)

RandomForestClassifier(random_state=123)

In [22]:
y_pred_rf = rfc.predict(X_test)

In [23]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred_rf)
cnf_matrix

array([[303,  23],
       [ 36,  59]])

In [24]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_rf))
print("Precision:",metrics.precision_score(y_test, y_pred_rf))
print("Recall:",metrics.recall_score(y_test, y_pred_rf))

Accuracy: 0.8598574821852731
Precision: 0.7195121951219512
Recall: 0.6210526315789474


In [25]:
y_pred_proba = rfc.predict_proba(X_test)[::,1]
auc = metrics.roc_auc_score(y_test, y_pred_proba)

In [26]:
print(auc)

0.903406522441072


In [35]:
f1_rf = metrics.f1_score(y_test, y_pred_rf)
print(f1_rf)

0.6666666666666667


In [ ]:
#Random Forest using oversampling

In [27]:
from imblearn.over_sampling import RandomOverSampler, SMOTE

In [28]:
ros = RandomOverSampler(random_state=123)
X_train_ros, y_train_ros= ros.fit_resample(X_train, y_train)

In [29]:
rfc = RandomForestClassifier(n_estimators=100, random_state = 123)
test_model = rfc.fit(X_train_ros, y_train_ros)
test_prediction = test_model.predict(X_test)

In [30]:
cnf_matrix2 = metrics.confusion_matrix(y_test,test_prediction)
cnf_matrix2

array([[293,  33],
       [ 29,  66]])

In [31]:
print("Accuracy:",metrics.accuracy_score(y_test, test_prediction))
print("Precision:",metrics.precision_score(y_test, test_prediction))
print("Recall:",metrics.recall_score(y_test, test_prediction))

Accuracy: 0.8527315914489311
Precision: 0.6666666666666666
Recall: 0.6947368421052632


In [32]:
y_pred_proba2 = test_model.predict_proba(X_test)[::,1]
auc2 = metrics.roc_auc_score(y_test, y_pred_proba2)

In [33]:
print(auc2)

0.8981272198902164


In [36]:
f1_rf2 = metrics.f1_score(y_test, test_prediction)
print(f1_rf2)

0.6804123711340206
